kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active
  namespace: testrollout
spec:
  selector:
    app: rollout-bluegreen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
